export const ROLES = {
  USER: "USER",
  TRAINER: "TRAINER",
  ADMIN: "ADMIN",
} as const;

export const FITNESS_GOALS = {
  BUILD_MUSCLE: "BUILD_MUSCLE",
  LOSE_FAT: "LOSE_FAT",
  GAIN_WEIGHT: "GAIN_WEIGHT",
  IMPROVE_STRENGTH: "IMPROVE_STRENGTH",
  IMPROVE_ENDURANCE: "IMPROVE_ENDURANCE",
  GENERAL_FITNESS: "GENERAL_FITNESS",
  ATHLETIC_PERFORMANCE: "ATHLETIC_PERFORMANCE",
} as const;

export const FITNESS_LEVELS = {
  BEGINNER: "BEGINNER",
  INTERMEDIATE: "INTERMEDIATE",
  ADVANCED: "ADVANCED",
} as const;

export const EXERCISE_CATEGORIES = {
  CHEST: "CHEST",
  BACK: "BACK",
  SHOULDERS: "SHOULDERS",
  BICEPS: "BICEPS",
  TRICEPS: "TRICEPS",
  FOREARMS: "FOREARMS",
  ABS: "ABS",
  QUADS: "QUADS",
  HAMSTRINGS: "HAMSTRINGS",
  GLUTES: "GLUTES",
  CALVES: "CALVES",
  FULL_BODY: "FULL_BODY",
  CARDIO: "CARDIO",
} as const;

export const EQUIPMENT_TYPES = {
  BODYWEIGHT: "BODYWEIGHT",
  DUMBBELL: "DUMBBELL",
  BARBELL: "BARBELL",
  CABLE: "CABLE",
  MACHINE: "MACHINE",
  KETTLEBELL: "KETTLEBELL",
  RESISTANCE_BAND: "RESISTANCE_BAND",
  SMITH_MACHINE: "SMITH_MACHINE",
  EZ_BAR: "EZ_BAR",
  PLATE: "PLATE",
  OTHER: "OTHER",
} as const;

export const RECORD_TYPES = {
  HEAVIEST_WEIGHT: "HEAVIEST_WEIGHT",
  MAX_REPS: "MAX_REPS",
  ESTIMATED_1RM: "ESTIMATED_1RM",
  MAX_VOLUME: "MAX_VOLUME",
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
} as const;
